### PR TITLE
Make use of Localisation_Toolkit units conversion methods

### LINKED ISSUE #207: Determine units from *UNIT file for results conversion
#### Description:

Use Localisation_Toolkit to handle unit conversion.

Make sure to update dependencies.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/Localisation_Toolkit/pull/32
https://github.com/BHoM/Localisation_Toolkit/pull/34
   
### Issues addressed by this PR

Closes #207 

**THIS PR HAS CONFLICTS WHEN REBASING AND HAS BEEN RERAISED AS** #234 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EgpBDqk08WJAhASpT-NvGUQB0GXBYspy1XwVj13huw8oAA?e=EbVhSu

### Changelog

- Added method to read units from an .mct file in the MidasCivilAdapter
- Added conversion methods when pushing/pulling data based on MidasCivil model units
- Force units include: Metric: N, kN, tonf and kgf Imperial: lbf and kips
- Length units include: Metric: m, cm and cm Imperial: ft and in
- Any combination of Imperial or Metric units can be used when pushing/pulling to MidasCivil

### Additional comments

I have set up 16 adapters to cover the different permutations for Imperial and Metric units. Can you check that the different between what has been pushed and pulled for the following. These are summarised in panels, they should all show 0.0 or < 1.0. A few spot checks in the software would be good too:
- [ ] `Node`
- [ ] `Constraint6DOF`
- [ ] `SectionProperty`
- [ ] `ShapeProfile`
- [ ] `SurfaceProperty`
- [ ] `MaterialFragment`
- [ ] `Load<T>`

There is a seperate model, folder and script for pulling results. I have already exported all the Excel files so you should just need to pull them and carry out some spot checks. 
- [ ] Results

**Note** When pulling back BoxProfile and FabricatedBoxProfile, they will be GeneralisedFabricatedBoxProfile and therefore the Warping Constant (J) will be zero. 

Any questions let me know.

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd can we have a chat about this on Monday. I have updated the `dependencies.txt` so the AzurePipeline is building correctly, but the AppVeyor builds are failing and it's because they're not building the Localisation_Toolkit, then raises a warning that `BH.Engine` does not contains the namespace `Units`.

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent happy to have a chat, however, I have just fixed AppVeyor and both builds are coming back successfully now if that's all the issue was? :smile:

**Comment by peterjamesnugent** [comment]
Perfect, thanks @FraserGreenroyd! Yeah, that's all it was.

**Comment by FraserGreenroyd** [comment]
Have added a `do-not-merge` label owing to this being a feature and @peterjamesnugent changing milestone. Label can be removed at end of this sprint.

**Comment by peterjamesnugent** [comment]
Compliance fail is a known issue and not deterimental to the source code, [referred to here](https://github.com/BHoM/Lusas_Toolkit/pull/272#issuecomment-662967835).

**Comment by peterjamesnugent** [comment]
@StephennipBH it looks to be a rounding error on MidasCivil's part, the error can get up to 0.2%, but like you said I don't think it should not have a massive impact on the functionality. I will email MidasCivil separately so they are aware.

Axial   force [kips] output from MidasCivil | Axial force converted from kips to   [N] | Axial force [N] output from   MidasCivil | Axial force converted from N to   [kips] | % difference between conversion to   Newtons and Newtons output | % difference between conversion to   Newtons and Newtons output
-- | -- | -- | -- | -- | --
-3.12 | -13878.45 | -13867.97 | -3.12029 | 0.08% | 0.01%
-3.05 | -13567.08 | -13547.02 | -3.04808 | 0.15% | -0.06%
-2.97 | -13211.22 | -13226.07 | -2.97587 | -0.11% | 0.20%
-2.9 | -12899.84 | -12905.13 | -2.90365 | -0.04% | 0.13%
-2.83 | -12588.47 | -12584.18 | -2.83144 | 0.03% | 0.05%

**Comment by peterjamesnugent** [comment]
@StephennipBH you can configure the style dialogue to output the results to more than 2 decimal places, that was the source of error. I have made an issue to include it when we write the documentation in Sprint 5: https://github.com/BHoM/MidasCivil_Toolkit/issues/233

**Comment by peterjamesnugent** [comment]
Closed due to rebase conflicts - reraised as #234 .

**Pull request closed without merging**
