### PR TITLE
Remove FEMeshToPanel

### LINKED ISSUE #379: Remove and version PanelToFEMesh method
#### Broken rules:

https://github.com/BHoM/MidasCivil_Toolkit/blob/develop/MidasCivil_Engine/Compute/FEMeshToPanel.cs

#### Suggestions to restore compliance:

https://bhom.xyz/documentation/Guides-and-Tutorials/Coding-with-BHoM/Versioning/versioning-guide/

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #379 

### Test files

By inspection.

### Changelog

- Removed `FEMeshToPanel` method that has since been replaced in the Structure_Engine in 4.2;

### Additional comments

@pawelbaran @IsakNaslundBh @michaelhoehn not sure if we specify how long the `ToBeRemoved` attribute should be included on a method before it's removed - might be worth specifying in the documentation:
https://bhom.xyz/documentation/BHoM_oM/Base_oM/Attributes/#toberemoved

### CODE REVIEW

**Comment by KalleEdstroem** [comment]
`PanelToFEMesh` is referenced in another method. This will need to be updated as well.

https://github.com/BHoM/MidasCivil_Toolkit/blob/63964235c2995c76a2baa92235b86b237303ce60/MidasCivil_Engine/Objects/MeshCentreComparer.cs#L59-L62

**Review by KalleEdstroem — COMMENTED** [review]
Happy with changes and removal of method. 
Tested. Able to build and able to push mesh. Code reaches `MeshCentreComparer` method and works as expected with the update.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by KalleEdstroem — APPROVED** [review]
Approving changes according to earlier comment.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check versioning

**Comment by peterjamesnugent** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Review by KalleEdstroem — APPROVED** [review]
No change in function. Only change is adding of .json versioning file. Inspected file and `MessageForDeleted`. Happy to approve based on comment above.

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
