### PR TITLE
Add support for MidasCivil 2022 

### LINKED ISSUE #334: Add support for MidasCivil 2022 v2.2
#### Parent issue(s) or Pull Request(s) causing the changes:

https://manual.midasuser.com/EN_Common/Civil/910/index.htm

#### Description:

Add support for MidasCivil 2022 v.2.2.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #334 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23335-Add%20support%20for%20MidasCivil%202022%20v2.2?csf=1&web=1&e=0l7Zcw

### Changelog

-  Added support for MidasCivil 2021 (all versions) to MidasCivil 2022 (up to v2.1) which only impacts `SurfaceProperty`, `Constaint6DOF` and `LoadCombination`
- Fixed bug where `AreaUniformlyDistributedLoads` were not being pushed as the parsing had been amended in 9.1.0.

### CODE REVIEW

**Comment by StephennipBH** [comment]
@peterjamesnugent The v.9.1.0 test script comes back with error on the MCT file.. I think it's good to also add a check for the 
pull of nodal load (I checked that pushed is fine). The current v9.1.0 nodal load would give an extra comma which wouldn't be able to read in the older version midas.  
image

**Review by StephennipBH — CHANGES_REQUESTED** [review]
The changes work as intended. I suggest there is an option to not have the 0 in the text if preferred but this is optional. 
image

Also should all the switch statement changes also apply to 9.0.5 and 9.0.0 so it doesn't just apply to 9.1.0?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Discussed with @peterjamesnugent offline and the comment by @StephennipBH has been addressed satisfactorily, with @StephennipBH stating that the changes do work, so deploying to alphas for further testing.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10608390041

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
