### PR TITLE
Added support for creating and reading TaperedProfile

### LINKED ISSUE #244: Add support for TaperedProfiles
#### Description:

Allow push and pull of TaperedProfiles applied to the different sections.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/992
https://github.com/BHoM/BHoM_Engine/pull/1980
   
### Issues addressed by this PR

Closes #244 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EoQuT-hlPLVJpbYy2JulBl4B9ZZJxhUHUUDXFB40ncF1cA?e=RDh0aQ

### Additional Comments
- @StephennipBH can you push/pull a few `SectionProfile` types please as I have made changes to that code too.
- MidasCivil only accepts the start and end profile.

### CODE REVIEW

**Review by StephennipBH — CHANGES_REQUESTED** [review]
T Section is pushed as solid circle instead.  Please review this part of code

**Review by StephennipBH — CHANGES_REQUESTED** [review]
Changes approved. It works as intended

**Review by StephennipBH — DISMISSED** [review]
Changes approved. it works as intended.

**Comment by peterjamesnugent** [comment]
Hi @StephennipBH, the error you were receiving when reading sections was due to the hybrid (i.e. `ISection` to `TSection`) being pushed. These are not supported in MidasCivil, so I have made sure they're caught and return a null. The push will record an error but still function.

Please can you do a check of the values that are being pushed pulled please.

**Pull request merged**
