### PR TITLE
Use encoding 1252 when appending lines to MidasCivil text files to allow for the use of special characters

### LINKED ISSUE #315: Properly Encode .txt files to use same encoding as .mct to ensure no loss of information
#### Description:
Current encoding of .txt files is default (for most this is utf-8), encoding for .mct files to be compatible with Midas needs to be ANSI.

#### Steps to reproduce:
Create text files, open in notepad (not the good one, the default one). Check if the encoding in the bottom right hand corner is ANSI. (Must include characters that depend on ANSI otherwise notepad will assume it is UTF-8, best way to check this is by adding a £ symbol in a name, tag or description.)

#### Expected behaviour:
Characters will not show up incorrectly.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/MidasCivil_Toolkit-%23315-AnsiEncoding?csf=1&web=1&e=C7xT72

### PR DESCRIPTION
**Pull request by calum-lockhart**
### NOTE: Depends on 
https://github.com/BHoM/MidasCivil_Toolkit/pull/299
   
### Issues addressed by this PR
Closes #315

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/MidasCivil_Toolkit-%23315-AnsiEncoding?csf=1&web=1&e=C7xT72

### Changelog

Changes to the encoding mechanism, to make the files ANSI compatible to allow special characters to push to Midas. 
Added encoding to file writing and file reading mechanisms.

### CODE REVIEW

**Comment by calumlockhart-bh** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — COMMENTED** [review]
Will the encoding ever change?

Might it be better to assign it as a variable and reuse that so the user can specify it as part of config, or it can be changed once in code instead of over 51 files? Thinking of future maintenance?

**Comment by calumlockhart-bh** [comment]
> Will the encoding ever change?
> 
> Might it be better to assign it as a variable and reuse that so the user can specify it as part of config, or it can be changed once in code instead of over 51 files? Thinking of future maintenance?

It seems unlikely that Midas will update the encoding, it seems pretty fundamental to the .mct file type because of its reliance on the * and ; characters.
However, my thoughts are the same and I've been thinking about assigning the encoding type in the adapter instead.
Will need to decide whether the variable can be assigned by the user, because the current .mct file format is pretty rigid on it being ANSI, and some users will not necessarily understand what they are setting.

**Comment by calumlockhart-bh** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Comment by calumlockhart-bh** [comment]
Any chance of a review on this?

**Review by StephennipBH — CHANGES_REQUESTED** [review]
I have tested it with an additional test script (saved under your testfile link) and there are issues with the text files created (see below). I believe it's due to the change to component `WriteToANSI`.

image

**Review by StephennipBH — COMMENTED** [review]
The changes work as intended. However, I would just like to check if we intend to change the delete and write all lines method on this PR.

**Comment by calumlockhart-bh** [comment]
@peterjamesnugent I believe you have made some changes to the Midas Civil toolkit, would it be possible to close out this pull requests with the changes you've made?

**Comment by peterjamesnugent** [comment]
Going to close for now as this affects quite a large portion of the toolkit and I am not convinced the changes to delete will give the same behaviour as the \develop branch.

**Pull request closed without merging**
