### PR TITLE
Migrate Convert methods to Adapter, change .MidasCivil namespace to Adapters.MidasCivil, add formatting to all documents and implement local versioning

### LINKED ISSUE #202: Change Adapter oM and Engine namespaces to External
#### Broken rules:

We want the menu items for Engine and oM classes defined in **Adapter-Based-Toolkits** (= only Toolkits that contain an Adapter project) into a new category, `Adapters`.

This is mainly to tidy up the menu items, to avoid clutter, and leaving the base Engine methods and classes on the top level.

Currently we have this situation:

What we want is:

This means:
1. **Take note of all changes you will be doing at the following points**.
2. Add the `Adapters` name to the namespace of all your oM and Engine classes.
3. This last point applies only for some Toolkits such as Lusas and Revit in the first picture above. Check if you have:
    - `BH.oM.Adapter.something` have to become `BH.oM.Adapters.something` (note the `s`); 
    - `BH.oM.External.something` have to become `BH.oM.Adapters.something`.
    - `BH.oM.Adapters.something` do not change them.
    - `BH.Engine.Adaper.something` have to become `BH.Engine.Adapters.something` (note the `s`);
    - `BH.Engine.External.something` have to become `BH.oM.Adapters.something`.
    - `BH.Engine.Adapers.something` do not change them.

### You must take note of what changes you've applied and list them in your PR.
E.g.
- All classes that were originally under `BH.oM.SAP2000` are now into `BH.oM.Adapers.SAP2000`
- All classes that were originally under `BH.Engine.SAP2000` are now into `BH.Engine.Adapers.SAP2000`
- All classes that were originally under `BH.oM.Adapter.SAP2000` are now into `BH.oM.Adapers.SAP2000` (note the `s`) 
- All classes that were originally under `BH.oM.External.SAP2000` (note the `s`) are now in `BH.oM.Adapers.SAP2000`

this will be used to inform the Versioning_Toolkit and make sure we get retro-compatibility for this change.

#### IMPORTANT NOTE
Note that the following **`using`s**:
```cs
using BH.oM.Adapter;
using BH.oM.Adapter.Commands;
```
```cs
using BH.Engine.Adapter;
```
```cs
using BH.Adapter.Modules.Structure
```

are **not to be changed** as they refer to the base Adapter namespace, which is not the subject of the current renaming.

### LINKED ISSUE #210: Migrate all Convert methods from Engine to Adapter
#### Broken rules:

Convert methods do not belong in the Engine as they offer no benefit to the user.

#### Suggestions to restore compliance:

Move Convert methods and any related methods to the Adapter.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_UI/issues/223
   
### Issues addressed by this PR

Closes #202 
Closes #210 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EsgzNkdXwkROqd9LxD_FE1gBGLS1NycVWKfBRzAhMopLmw?e=vdFQq7

### Changelog

- Moved methods in `.MidasCivil` namespace to `.Adapters.MidasCivil` namespace
- Implemented localised versioning for `MidasCivil_Engine` stored in `Versioning_32.json`
- Ported all `Convert` methods from `MidasCivil_Engine` to `MidasCivil_Adapter`
- Added formatting (i.e. headers, line breaks etc.) to all document files 
- Added exceptions to `CombineTextFiles` and `MidasCivilAdapter` for files that do not exist

### Additional comments
@calumlockhart-bh this one should be a lot easier as there are no objects in the MidasCivil_oM, and the only method that needs to be checked is the CombineTextFiles which is in the `PushPull.gh` file (far right). Most of the Engine methods have been moved to the Adapter.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@peterjamesnugent Would you mind raising a PR on Versioning_Toolkit, covering the changes to Midas and Lusas. Can then either merge that one as is, or wait for others to join in with the external changes if needed.

**Comment by FraserGreenroyd** [comment]
Now the versioning can be done locally on this toolkit, @peterjamesnugent , same as we did on XML_Toolkit? :smile:

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent before you merge you might want to take a look at the issue I commented on on BHoM_Adapter which might impact this?

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd yeah I will leave it open for today, I have made my changes in line with this [comment](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-597186509).

**Comment by FraserGreenroyd** [comment]
Might be worth updating the PR title then @peterjamesnugent as that still says external? :smile: same for Lusas I'm guessing?

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd  dammit, I knew I missed something! Good spot. The [Lusas PR](https://github.com/BHoM/Lusas_Toolkit/pull/240) has already been merged on Friday based on the comment I linked.

**Pull request merged**
