### PR TITLE
Upgrade adapter for MidasCivil 2024 v1.1 and 2.1 

### LINKED ISSUE #382: Review changes in MidasCivil 2024 v1.1
#### Description:

https://patch.midasit.com/00_mods/en/01_program/Civil/04_Release_Note/Civil%202024%20%28v1.1%29%20Release%20Note.pdf

Appendix previously detailed changes (but has not done for a while):
http://manual.midasuser.com/EN_Common/Civil/945/index.htm

### PR DESCRIPTION
**Pull request by EmmaSander**
### Issues addressed by this PR

Closes #382 

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/MidasCivil_Toolkit/%23390-review-changes-in-midascivil-2024-v11?csf=1&web=1&e=WVmTn8

### Changelog
- Added functionality for Midas Civil 2024 v1.1 and v2.1;

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Review by rhodessophie — CHANGES_REQUESTED** [review]
Not pulling through the area uniformly distributed loads. Same error with the Area temperature loads.

> 1. This component failed to run properly.
> - Error: An item with the same key has already been added.
> - Occured in  BH.Adapter.BHoMAdapter.GetCachedOrReadAsDictionary[TId,TObj](IList ids, ActionConfig actionConfig)
>      called from BH.Adapter.BHoMAdapter.GetCachedOrRead[T](IList ids, String tag, ActionConfig actionConfig)
> - Are you sure you have the correct type of inputs? Check their description for more details.

**Comment by EmmaSander** [comment]
Issue discussed offline, will be resolved separately. Not related to the Midas version.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Review by rhodessophie — APPROVED** [review]

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Comment by peterjamesnugent** [comment]
Thanks @EmmaSander and @rhodessophie! Looks good.

**Review by rhodessophie — APPROVED** [review]
Happy to approve after talking through the error with Emma.

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
