### PR TITLE
Update Assembly Version

### PR DESCRIPTION
**Pull request by BHoMBot**
Updates Assembly Version to 4.3

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from a CI/CD perspective.

**Review by peterjamesnugent — APPROVED** [review]
LGTM.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2988424642

**Pull request merged**
