### PR TITLE
Bug fixed for reading Constraint6DOF with default support group (i.e. no name)

### LINKED ISSUE #303: Support that doesn't contain a group name can't be pull back to BHoM.

### PR DESCRIPTION
**Pull request by StephennipBH**
### Issues addressed by this PR

Closes #303 

### Test files

[Test File](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=bIKi6w&xsdata=MDV8MDF8fDQxMmY5YjU0YWE5ZTQ4OTZkZjU4MDhkYTgwNzk3OTdlfDUwZWU2NDE4ODY5ZTQ4ZjVhOTgyMzYwN2ZjZWUxZTFkfDB8MHw2Mzc5NjM1NTY0NDQxMDI0ODh8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2YldWbGRHbHVaMTlaVkdOM1RXMVpkMDFFUlhSTmVtTXhXbWt3TUU1NlFtdE1WMHBzVDBkSmRFMVVXVFZQUkVFeFRucHJkMWxVVlRWQWRHaHlaV0ZrTG5ZeXx8&sdata=UzJKQnNHMjdkenp0MVAwcHJvRFVtcnpQVnlpcDM2emhYZld2OGpsU05WOD0%3D&ovuser=50ee6418%2D869e%2D48f5%2Da982%2D3607fcee1e1d%2Cstephen%2Enip%40burohappold%2Ecom&OR=Teams%2DHL&CT=1660760186928&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA3MDMwMDgxNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=db9e0d78%2D5456%2D49d2%2D8529%2D2d43b6c192e2&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FMidasCivil%5FToolkit%2F%23303%2DAdd%20pulling%20supports%20without%20ID&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b
)

### CODE REVIEW

**Comment by jtrainor1** [comment]
Works as intendede

**Comment by jtrainor1** [comment]
Works as intended.

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
See comments. 

I haven't had a chance to run the test script but we need to cover the following scenarios:
- Spring with name (i.e. pushed from BHoM)
- Constraint6DOF with name (i.e. pushed from BHoM)
- Spring without name 
- Constraint6DOF without name

The above in an .mct for 8.9.5 and in 8.7.5  (default in the `switch` cases.

If we can pull all of those without error then we are good.

**Review by peterjamesnugent — APPROVED** [review]
I've tested this for the following versions: 
- v8.8.1 
- v8.8.5
- v8.9.5
There was a change to how springs are parsed in v8.8.5 and this has been captured in the PR sufficiently.

There is a slight nuance with the `switch` statements where it defaults to previous versions which should be updated, outside the scope of this PR and covered in #334.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
