### PR TITLE
Fix bug in CompareLoadGroup

### LINKED ISSUE #307: Pushing PointLoad with similar name as BarPointLoad results in it not being pushed
#### Description:

`BarPointLoad.Name = "BarPointLoad-1";
`PointLoad.Name = "PointLoad-1";

This fails to push because the `CompareLoadGroup()` method using contains instead of an equality check.

#### Steps to reproduce:

See test script.

#### Expected behaviour:

Ability to push `PointLoad` with name that may be contained in other load names.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/Installers/Scripts/BuroHappold_BHoM_v4.2/Structures%20-%20Create%20read%20loads?csf=1&web=1&e=IbHwj6

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #307 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/Installers/Scripts/BuroHappold_BHoM_v4.2/Structures%20-%20Create%20read%20loads?csf=1&web=1&e=IbHwj6

### Changelog

- Fixed a bug where loads with names that were contained in load names already pushed would not be pushed. For example a `barPointLoad.Name = BarPointLoad-1` is pushed, trying to push `pointLoad.Name = PointLoad-1` would not succeed,
- Fixed a bug where the `BarDifferentialTemperatureLoad` was not assigned a Load Group in MidasCivil corresponding to its name

### CODE REVIEW

**Review by AntigoniChatzidaki — APPROVED** [review]
Works as expected. Tested using MidasCivil 2020 v3.2.

**Review by StephennipBH — COMMENTED** [review]
see comment below.

**Review by StephennipBH — DISMISSED** [review]
The changes work as intended. Changes approved.

**Comment by peterjamesnugent** [comment]
A review so nice he left it twice 😄

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Review by AntigoniChatzidaki — APPROVED** [review]
Names are passed correctly.

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Review by StephennipBH — APPROVED** [review]
I checked it with a different test script as there were errors when trying to read the MCT file through Midas. Changes work as intended.

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
