### PR TITLE
Align with changes to BarUniformTemperatureLoad and AreaUniformTemperatureLoad

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1074
https://github.com/BHoM/BHoM_Engine/pull/2138

### Changelog

- Align with changes from `BarTemperatureLoad` and `AreaTemperatureLoad` to `BarUniformTemperatureLoad` and `AreaUniformTemperatureLoad`

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check code compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check documentation compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check project compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
> Fixed code compliance for first letter of object name to lowercase

I approve :wink:

**Comment by peterjamesnugent** [comment]
@BHoMBot check code compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check code compliance

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd the `ObjectNameMatchesFileName `check that is failing is not applicable:

> This check is for object classes only within an oM.

https://github.com/BHoM/documentation/wiki/ObjectNameMatchesFileName

Is there a way to stop it checking this?

**Comment by peterjamesnugent** [comment]
@BHoMBot check documentation compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check project compliance

**Review by IsakNaslundBh — APPROVED** [review]
Approving based on code review

**Comment by IsakNaslundBh** [comment]
Also, the outstanding compliance check can be ignored for this PR, as out of scope for the PR.

**Pull request merged**
