### PR TITLE
Add support for MidasCivil 2023 v1.1 and bug fixes

### LINKED ISSUE #341: Beam element with beam end released can't be pulled back
Beam end release can't be pulled

version used 8.9.5

### LINKED ISSUE #351: Upgrade to MidasCivil 2023 v1.1

### LINKED ISSUE #353: Changes to RigidLink to be reflected in Adapter
#### Description:

`RigidLink` format has changed.

#### Steps to reproduce:

Push `RigidLink` to Version 9.0.0 or above and try to load.

#### Expected behaviour:

Push `RigidLink`.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23353%20Fixes%20for%20RigidLink/%23353%20Bug%20fix%20for%20RigidLink.gh?csf=1&web=1&e=e5mCfu

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #341 
Closes #351 
Closes #353 

### Test files

[Push/Pull Elements](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23351%20Add%20support%20for%20MidasCivil%202023%20v1.1/BuroHappold_BHoM_v6.1.beta_Create%20-%20read%20-%20elements%20-%20bridges.gh?csf=1&web=1&e=euHVY5)

[Push/Pull Loads](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23351%20Add%20support%20for%20MidasCivil%202023%20v1.1/BuroHappold_BHoM_v6.1.beta_Create%20read%20loads.gh?csf=1&web=1&e=uWBM23)

[Push/Pull `RigidLink` and `BarRelease`](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23353%20Fixes%20for%20RigidLink/%23353%20Bug%20fix%20for%20RigidLink.gh?csf=1&web=1&e=e5mCfu
)
### Changelog

Added functionality for MidasCivil 2023 v1.1
Added changes to `RigidLink` following changes from Version 9.0.0
Fixed bug where `BarReleases` were not pushing/pulling correctly (unrelated to versions)

### Additional comments

If we want to test things separately please tick the boxes below:
- [x] Tested MidasCivil 2023 v1.1 elements and properties
- [x] Tested MidasCivil 2023 v1.1 loads
- [x] Tested `RigidLink` fixes
- [x] Tested `BarRelease` fixes

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by StephennipBH — COMMENTED** [review]
Only reviewing the rigid link and beam end releases. Here are the following issues I found with the pulling back for beam end release and rigid link. The rigid link comes back false rather than true in XtoX YtoY ZtoZ. The beam end release comes back null
image
image

**Comment by jtrainor1** [comment]
Reviewing the push/pull of loads to MIDAS civil, I've found some issues with the temperature loading. Firstly, the bar uniform temperature loading is only pushing one of the two load specified to the text file. 
image

Only the +2 degree change is being pushed to the text file currently. 

image

Next the area differential temperature is bringing other uniform temperature loads that do not centre the value to 0. 

image

For example, in the above image. A temperature differential of 13 to -1, I would assume it would add +1, not +6 as a uniform load.

**Comment by peterjamesnugent** [comment]
@jtrainor1 the first issue was because the load had the same name, so it invoked `Delete` and `Update` - hence it overwrites and only appears that one load has been pushed. I have updated the script so the loads have unique names.

Regarding the `AreaDifferentialTemperatureLoad` I found a bug where the unit conversion was not working properly (so if you test it in F it will push/pull properly.

Regarding the comment about the offset being in correct, for a `TopTemperature = 13` and `BottomTemperature = -1`, Midas will centre the differential element about 0, so it will have `Top Temperature = + 7` and `BottomTemperature = -7` so the required offset will be +6. This has come up quite a bit so I will add a section to the Wiki,

**Comment by peterjamesnugent** [comment]
Wiki updated here: https://github.com/BHoM/MidasCivil_Toolkit/wiki/MidasCivil-Specific-Adapter-Features#areadifferentialtemperautreload

**Review by elizawren — DISMISSED** [review]
Spot checks of node/bars/FEMesh locations as well as section properties, everything checked was ok

**Comment by jtrainor1** [comment]
Still some issues with pushing the uniform bar temperature loading: 

image

No -2 found. 

Also in the grasshopper script itself I see 4 loads, is this correct?:
image

**Review by StephennipBH — APPROVED** [review]
Bug regarding pulling bar release have been addressed and fixed. Push/pull of bar release and rigid link work as intended

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by jtrainor1 — APPROVED** [review]
I have checked how loads are pushed and pulled into Midas Civil. I have checked the following load types:
- Bar temperature loads
- Self weight
- Bar uniform and varying loads
- Bar point loads
- Point loads
- Area uniform loads 
- Area uniform and differential temperature loading 

These are all functioning correctly.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check versioning 
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, ready-to-merge

**Pull request merged**
