### PR TITLE
Remove use of CustomData and make use of new Fragment for AdapterId

### LINKED ISSUE #261: Remove use of CustomData in the code
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Elements\ToBar.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Elements\ToFEMesh.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Elements\ToNode.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Elements\ToPanel.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Elements\ToRigidLink.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToAreaTemperatureLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToAreaUniformlyDistributedLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToBarPointLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToBarTemperatureLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToBarUniformlyDistributedLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToBarVaryingDistributedLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToGravityLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToLoadcase.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToLoadCombination.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Loads\ToPointForce.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Properties\ToBarRelease.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Properties\ToConstraint6DOF.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Properties\ToMaterials.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToBHoM\Properties\ToSurfaceProperty.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToMidasCivil\Elements\FromBar.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToMidasCivil\Elements\FromFEMesh.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToMidasCivil\Elements\FromNode.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToMidasCivil\Elements\FromRigidLink.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToMidasCivil\Properties\FromMaterial.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToMidasCivil\Properties\FromSectionProperty.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Convert\ToMidasCivil\Properties\FromSurfaceProperty.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Elements\Element.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Elements\Node.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\AreaTemperatureLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\AreaUniformlyDistributedLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\BarPointLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\BarTemperatureLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\BarUniformlyDistributedLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\BarVaryingDistributedLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\Loadcase.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\LoadCombinations.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Create\Loads\PointForce.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Elements\Bars.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Elements\FEMeshes.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Elements\Nodes.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Elements\RigidLinks.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Loads\AreaTemperatureLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Loads\AreaUniformlyDistributedLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Loads\BarPointLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Loads\BarTemperatureLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Loads\BarUniformlyDistributedLoad.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Loads\BarVaryingDistributedLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Loads\LoadCombinations.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Loads\PointForces.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Properties\SectionProperties.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\CRUD\Read\Results\ReadResults.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\PrivateHelpers\CombineLoads.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\PrivateHelpers\CreateGroups.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Adapter\Type\NextFreeId.cs

 - [ ] MidasCivil_Toolkit\MidasCivil_Engine\Compute\FEMeshToPanel.cs

</p>
</details>

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1033
https://github.com/BHoM/BHoM_Engine/pull/2106

 ### Issues addressed by this PR

Closes #261 

Aligning with changes in https://github.com/BHoM/BHoM/issues/1012

 

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EiJywS8APoBAg7RiC4c0rRsBlYH8jZvgGJS4f6PlobSbaA?e=w0KZrC

 ### Changelog

- Removes the use of `CustomData` and `MidasCivilId` will now be stored as `Fragments`

### CODE REVIEW

**Review by alelom — APPROVED** [review]
Approving on the basis of code changes.
Could not test scripts with Midas due to a licensing problem on my machine.

**Review by StephennipBH — CHANGES_REQUESTED** [review]
The Section Properties of bars don't return with the correct IDs that are shown on Midas when pulling.

**Review by StephennipBH — APPROVED** [review]
The changes have fixed Section Properties ID. Changes approved

**Pull request merged**
