### PR TITLE
Update Assembly Version

### LINKED ISSUE #200: Update AssemblyFileVersion
The `AssemblyFileVersion` attribute should now be updated to read `3.2.0.0` for all `AssemblyInfo.cs` files within this repository for the start of the 3.2 milestone

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #200

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd CheckInstaller is failing for some reason?

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent yeah slight problem that @IsakNaslundBh and I have resolved, should work now. Sorry!

**Comment by peterjamesnugent** [comment]
Cheers @FraserGreenroyd all is forgiven 😄

**Pull request merged**
